name: Build dev
on:
  push:
    branches:
      - dev
jobs:
  build_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        with:
          sdk-channel: dev
